### ISSUE TITLE
Crash after loading world, sometimes before.  1.18.2

### ISSUE THREAD

**Issue by Lozf** [Reforged-Mods/Terrestria-Reforged#11]
**Description of the Bug**

When loading into a world, or within a couple of minutes of running around, always; it crashes.  I am using both mods that are required to run Terrestria.

**To Reproduce**

1. Place block '...'
3. See '...'

Simply loading into the world and running around.

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: https://gist.github.com/Lozf/970b191323bb7f4c2626023ffaeaf329

 - Crash report (If available):  
 - [crash-2023-05-30_16.18.22-client.txt](https://github.com/Reforged-Mods/Terrestria-Reforged/files/11607282/crash-2023-05-30_16.18.22-client.txt) 

**Additional context**

**Comment by Trinsdar** [comment]
Can you put the crash report on gist as well please?

**Comment by Lozf** [comment]
sure, here you go!  https://gist.github.com/Lozf/69eec23922be8b69fe7d2097c703ba0d

**Comment by Trinsdar** [comment]
Honestly not sure what's causing that, as i don't see any reference to any terraform code, but can you reproduce the crash without optifine?

**Comment by Lozf** [comment]
I just tried it, and yes it does still crash, here are the newest reports:

https://gist.github.com/Lozf/c11f81943d90f7e1261b7523ed9b9d76
https://gist.github.com/Lozf/370eac1e69847acf5a9b329e7e455ae3

**Comment by Trinsdar** [comment]
ok I need more info:
does it happen without terrestria but with terraform and fabricated forge api?

**Comment by Lozf** [comment]
It doesn't seem to be happening with Terrestria removed.  And thinking about before when I had it installed I always logged in and went straight to a Terrestria biome where it would crash- if it didn't crash immediately.

**Comment by Trinsdar** [comment]
Ok this time can you remove canary and try to reproduce it?
I have a suspicion of what the cause is, this will either prove or deny it.

**Comment by Lozf** [comment]
So this is interesting, with Canary off now the biomes won't load, like it just stops generating.  I can't tell if its only Terrestria biomes, or more than that since it says "waiting for chunk" then never does.  I do know when I locate and teleport to Terrestria biomes it's just sky.  No crash log, but here's the latest.log: https://gist.github.com/Lozf/e38808caed5946fa155f1a40ee5c58b1
Minecraft biomes seem to have no trouble loading.
![2023-05-31_22 41 52](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/69091548/7bfc055e-a89e-4ff7-b29d-d1c070be5595)

**Comment by Trinsdar** [comment]
https://cdn.discordapp.com/attachments/647507964873408532/1114043351067525171/terrestria-4.0.6.2-test1.jar
I think this fixes the crash, as for the worldgen issue, I have no idea at the moment cause that log doesn't tell my what I need to know. try reproducing it without optifine, as I cannot reproduce that issue you ran into

**Comment by Lozf** [comment]
So I tried both with optifine and without optifine, and it still crashes. 
With optifine latest log: https://gist.github.com/Lozf/abc8e990059d887974c2221a376ef356
with optifine crash: https://gist.github.com/Lozf/5d55cce51b91e451a852c336f0137a97

Without optifine latest log: https://gist.github.com/Lozf/5ba04840332fcde41f0bc7ecc420f5c8
Without optifine crash: https://gist.github.com/Lozf/647ef2830f7c0fb940883bf835a8c95d

Taking off canary results in loading in to sky and nothing else.
Taking off canary and optifine results in regular Minecraft biomes spawning but Terrestria ones being only sky.

**Comment by Lozf** [comment]
I just tried this with Traverse, taking off fabric biome API reforged and Terrestria, and the crash happened with Traverse too.
latest log: https://gist.github.com/Lozf/a242a7d4d6a125d1a6e1f97062a82c9b
crash report: https://gist.github.com/Lozf/166c6f5e26aede002523dc23ffa42c47

- Also, some resource packs for the traverse mod don't seem to be loading; for example, the coniferous trees were purple and black.

**Comment by Trinsdar** [comment]
Can you provide me with the modpack your using? I'm guessing it's one of the mods in there, cause i haven't been able to reproduce this issue

**Comment by Lozf** [comment]
Since it's just a random assortment of Mods I'll go through and do the elimination method and get back to you with which one seems to be causing it, if that works for you?

**Comment by Trinsdar** [comment]
Yah that works

**Comment by Lozf** [comment]
Welp, after testing in batches it only seems to happen when all the mods are together.  Guess it's time to trim the mod list!
