### ISSUE TITLE
[1.18.2]  Frame drops in Hemlock Forest, incompatibility with Immersive Weathering

### ISSUE THREAD

**Issue by Reshy** [Reforged-Mods/Terrestria-Reforged#13]
**Description of the Bug**
Frame drops in the Hemlock forest, in addition they don't seem to be having their transparency set correctly.

**To Reproduce**
1.  Use the common performance boosting mods and Immersive Weathering
2. Enable Alt+F3
3. Go to a hemlock forest.
4. Notice the frame drops.

**Expected behavior**
Frame drops shouldn't be happening.

**Screenshots & Video**
![2023-07-15_08 02 49](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/2096384/597a9b8e-1a81-41b8-bcfd-3d5075687a05)
![2023-07-15_08 03 09](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/2096384/8dd88ab2-f812-4302-bb5f-1063c66121d1)
![2023-07-15_08 05 12](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/2096384/3f133bf9-f5b6-483a-abff-4b3c25974e5d)

**Logs & Environment**
https://pastebin.com/TbH6YMuL
 - Full log:  Too Large, error prints for every individual leaf block.

**Comment by Reshy** [comment]
Also happens with redwood leaves:

![2023-07-15_08 15 18](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/2096384/9097a8fc-f9ce-41a6-b5e1-90ca35b050f3)

Pausing the game seems to remove the FPS lag, there doesn't seem to be any tick-lag.  The lag only happens when up close to the leaves, from far away the frame rate is stable:
![2023-07-15_08 16 37](https://github.com/Reforged-Mods/Terrestria-Reforged/assets/2096384/622e36de-c4d9-47b1-9ddb-b4690fc76146)

**Comment by Trinsdar** [comment]
ok so just tested, it happens with the original fabric version as well, however I don't think this is an issue on terrestria fabric side either, I think this is entirely an immersive weathering issue

**Comment by Trinsdar** [comment]
ok turns out there were already issue reported: https://github.com/TerraformersMC/Terrestria/issues/279
https://github.com/AstralOrdana/Immersive-Weathering/issues/174

**Comment by Reshy** [comment]
It might be, though no other biome adding mod has this issue, not even Traverse or Cinderscapes.  I'm guessing it's related to the "falling leaves" effect not working right with the leaf blocks here, and something is causing them to be solid blocks instead of transparent.

**Comment by Trinsdar** [comment]
Yah i already know the cause, immersive weathering logs every tick if the leaf found is not an instance of LeafBlock, which terrestria's are not, which causes the lag. Quite stupid piece of code imo, not even sure why that check is needed
