### ISSUE TITLE
Grass in tropical islands don't show dirt texture

### ISSUE THREAD

**Issue by Deadlydiamond98** [Reforged-Mods/Terrestria-Reforged#4]
In the Volcanic islands biomes the grass block is missing part of its texture, the blocks texture won't show anything other than the top grass
![Screenshot from 2021-09-14 16-13-05](https://user-images.githubusercontent.com/90122895/133327430-f0981d8d-1ef0-402c-9e84-8deedd9ff1b3.png)
 part.

**Comment by Trinsdar** [comment]
uhhh that's annoying
