### ISSUE TITLE
[Mod Compat] Visual error with Caves and Cliff Backport

### ISSUE THREAD

**Issue by Cixon** [Reforged-Mods/Terrestria-Reforged#5]
Tested on Forge 36.2.4
Latest Terrestria & Cave and Cliff

**Link:** https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport

Not sure if it has something to do with the mixins or what but was a bit interesting nonetheless. Biomes do seem to work just fine with CCB’s world generation as of now.

**Error:**
![4EC66698-C3AC-4E73-B452-1916C92A709D](https://user-images.githubusercontent.com/69068153/133384798-1112f85f-46ae-4d0b-8902-da7d40645450.png)

**Comment by PhweeDev** [comment]
That is hideously beautiful. It should be noted that CCB is being rewritten. However. That may be on Trinsdar's list to investigate

**Comment by Trinsdar** [comment]
Hm not actually sure if it is my issue, i would need the opinion of the CCB dev
Edit: also it'd be very difficult to investigate cause the mod is closed source, i really hate when mods are closed source.

**Comment by ItsBlackGear** [comment]
i'm as confused as you, i haven't seen that thing before

**Comment by ItsBlackGear** [comment]
@Cixon what's your modlist so far?

**Comment by Cixon** [comment]
> @Cixon what's your modlist so far?

Hmm...well; I was using CCB, Terrestria, Better Nether and Cinderscapes and a mod called Halogen.

Though through further investigation, Halogen is a forge mod that ports sodium, some features of lithium and a little bit of phosphor which could most likely be the issue here?

Mod link(s): https://www.curseforge.com/minecraft/mc-mods/halogen

https://www.curseforge.com/minecraft/mc-mods/betternether-reforged

**Comment by Cixon** [comment]
However I should note that some terrestria biome chunks would not load properly; such as the chunk would be blacked/hallowed out and when trying to update it with a touch placement or breaking a block in that chunk, the client would crash.

**Comment by ItsBlackGear** [comment]
hmmm i'm a bit suspicious about halogen, can you test without it?

**Comment by Cixon** [comment]
> hmmm i'm a bit suspicious about halogen, can you test without it?

I will test it out later. I have work soon..😅

**Comment by Cixon** [comment]
Seems to me to be a Halogen issue. Will redirect it to their github instead.

Sorry, false alarm!
