### ISSUE TITLE
hey so i am trying to make a mod pack and some of the biomes in the mod are identical to biomes in some over mods so i want to get rid of the biomes from this mod but when i look theres no config is this a bug or are you working on adding it

### ISSUE THREAD

**Issue by mrnanner** [Reforged-Mods/Terrestria-Reforged#7]
**Description of the Bug**

**To Reproduce**

1. Place block '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by Trinsdar** [comment]
there is a config, I'm not sure if it fully works or not though

**Comment by mrnanner** [comment]
so is there anything i can do or do i just have to deal with it

**Comment by Trinsdar** [comment]
well look in config/terrestria/biomes.json

**Comment by mrnanner** [comment]
thanks i found it it was in a file folder thanks for the forge port btw

**Comment by mrnanner** [comment]
so umm uhh sorry im new to github and i thought that that was for extra info sorry

**Comment by mrnanner** [comment]
i made my acount the fucking day i talked to you about the bug for crying out loud
