### ISSUE TITLE
so we meet again well the config didint work but that semes to be an issue allready so is the structures not spawning bug but im not here for that im here to complain about im here to complain about how all my configs were set to the normal configuration for some rason im lucky i didint have some sort of heavy configuration or i wuld have screamed (im using the configured mod btw ) please fix this

### ISSUE THREAD

**Issue by mrnanner** [Reforged-Mods/Terrestria-Reforged#9]
**Description of the Bug**

**To Reproduce**

1. Place block '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by Trinsdar** [comment]
Ok please stop putting everything in the title and actually use the description,  that's what it's there for. If this were any other repo you would get completely ignored for doing this dumb shit. 
Also this would be.a duplicate,  you should've just commented on the existing one that it didn't work
